fea: added add task functionality
vzsoares/todo-list pull request #1
Opened 2022-04-02 00:41 UTC by vzsoares

added the functionality to add typed task to ui
 before
![image](https://user-images.githubusercontent.com/86134825/161356891-837b6f4f-65c1-4a61-923c-b57f5cbcfa5f.png)
after
![image](https://user-images.githubusercontent.com/86134825/161356942-d9a9f4dc-d802-4dba-bb1b-87b9c25c5560.png)

2022-04-02 14:49 UTC, frattezi requested changes
Muito bom Zenha! Vi que você já conseguiu resolver toda a lógica necessária para as ações da nossa aplicação, precisamos apenas melhorar a utilização dos tipos, considere minha reorganização sobre seu principal objeto taskList, pode te auxiliar a simplificar algumas estruturas do seu código.

Notei que você fez uma grande alteração no yarn.lock. Este arquivo deve se manter estável durante o desenvolvimento, e alterado apenas em dois casos:
- Se adicionarmos ou removermos alguma biblioteca
- Se deliberadamente desejarmos atualizar ou desatualizar alguma biblioteca.

Tirando estas duas situações o file deve se manter estável, muitas vezes, a troca de versão de dependências e subdependências pode quebrar o código atual, este é inclusive o objetivo deste file, manter tudo na mesma versão.

Como existem mais de sete mil mudanças no file e nenhum novo pacote adicionado ao `package.json`, acredito que em algum momento você pode ter o deletado e durante a reinstalação dos pacotes o próprio yarn baixou diversas dependências mais atualizadas.

Tente, utilizando o git, desfazer as mudanças apenas para este file, atualizando-o com a branch main.

2022-04-02 14:49 UTC, frattezi commented on src/App.tsx
> +    exampleTask: { task: 'Model Task Example', completed: false, id: '123456' },
Eu gostei bastante da forma como você organizou o Objeto de task aqui, eu apenas modificaria o state `taskList` para, ao invés de ser um objeto com diferentes nomes {exampleTask: {}}, para uma listas de objetos do tipo Task[] E.g [{}, {}, ...], uma vez que as chaves com os nomes das task (exampleTask por exemplo)  não necessáriamente precisa ser utilizada, seu objeto Task já possui um id único não?

2022-04-02 14:49 UTC, frattezi commented on src/App.tsx
> +        taskList={taskList}
Você poderia criar uma função neste arquivo como:

```js
  const addTask = (task: TaskListItem, newKey: string): void => {
    setTaskList({ ...taskList, [newKey]: task });
  };
```

Assim, não seria necessário passa `taskList` e `setTaskList` como props, apenas a função `addTask`.
Repare que será necessário ajustar os exports de seus tipos.

2022-04-02 14:49 UTC, frattezi commented on src/components/AddItemForm.tsx
> +interface TaskListItemMap {
Considere a simplificação que mencionei acima, sobre sua taskList ser uma lista de tasks, e não um objeto de tasks demarcados por datetime.

2022-04-02 14:49 UTC, frattezi commented on src/components/AddItemForm.tsx
> +type TaskListItem = {
Este tipo surge em outros pontos do código porém não está exportado, será que é dai que vem os tipos `any`?

2022-04-02 14:49 UTC, frattezi commented on src/components/AddItemForm.tsx
> +  setTaskList: (value: any) => void;
Any? Nós sabemos qual é o tipo esperado para esta operação, não?

2022-04-02 14:49 UTC, frattezi commented on src/App.tsx
> +    exampleTask: { task: 'Model Task Example', completed: false, id: '123456' },
O nome me indica que é uma lista, porém recebemos um objeto

2022-04-02 14:49 UTC, frattezi commented on src/App.tsx
> +    exampleTask: { task: 'Model Task Example', completed: false, id: '123456' },
é possível pré declarar o tipo aqui também, para o useState

2022-04-02 14:49 UTC, frattezi commented on src/components/AddItemForm.tsx
> +  }
Como mecionei no código do App, utilizando a função addTask:
```suggestion
  const domInputId = 'new-todo-input';
  function handleAddTask(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();

    if (userInput) {
      const uniqueTaskID = String(new Date().valueOf());
      const newTask = {
        task: userInput,
        completed: false,
        id: uniqueTaskID,
      };
      addTask(newTask, uniqueTaskID);
    }
  }
```

Assim, será necessário apenas passar o update para a função, e não o estado como um todo. ^^

Considere que isto se relaciona também com o formato do `taskList`. Perceba que tanto no meu código quanto no seu estamos replicando a chave `uniqueTaskID` em dois níveis do nosso objeto, precisamos mesmo deste dado salvo 2x? Daqui nasce a sugestão de mudança para uma Task[] ou seja:
`[{id: uniqueTaskID, completed: false, task: typedTask }]`

2022-04-02 14:49 UTC, frattezi commented on src/components/Task.tsx
> +  taskList: any;
Já conhecemos e definimos este tipo, precisamos apenas importar e usar.

2022-04-02 14:49 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +type TaskListItem = {
Precisamos reorganizar e compartilhar, se tiver dúvidas nessa parte pode me chamar. Pense que, onde a taskList é feita é necessário se explicitar seu tipo, e assim, outros utilizadores vão saber oque pode ou não ser passado como uima taskList.

2022-04-02 14:49 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +interface TaskListItemMap {
Acredito que o mamão e o Gil podem ter idéias legais de unique Id aqui.

2022-04-02 14:55 UTC, frattezi commented
Gostei muito que você colocou fotos e uma descrição no seu PR, aqui são apenas alguamas sugestões para deixar sua apresentação ainda melhor:
- Se marque como asignee no PR, a opção fica no canto direito na tela, é só clicar e selecionar seu usuário. Isto diz para os devs que você é o responsável atual pelo PR e seu merge.
- Adicione a label de enhancement ao seu PR, indica que você desenvolveu uma nova melhoria ou feature ao seu projeto, e deixa clara a itenção do seu PR para os reviewers.

Sugestão para o Readme, use e abuse do **markdown** aqui um exemplo:

```markdown
## Context
Added the functionality that allows users to add a new Task to  the todoList.

## UI Demo
**Before**
...
**After**
...
```

2022-04-02 21:26 UTC, vzsoares commented
> Muito bom Zenha! Vi que você já conseguiu resolver toda a lógica necessária para as ações da nossa aplicação, precisamos apenas melhorar a utilização dos tipos, considere minha reorganização sobre seu principal objeto taskList, pode te auxiliar a simplificar algumas estruturas do seu código.
> 
> Notei que você fez uma grande alteração no yarn.lock. Este arquivo deve se manter estável durante o desenvolvimento, e alterado apenas em dois casos:
> 
> * Se adicionarmos ou removermos alguma biblioteca
> * Se deliberadamente desejarmos atualizar ou desatualizar alguma biblioteca.
> 
> Tirando estas duas situações o file deve se manter estável, muitas vezes, a troca de versão de dependências e subdependências pode quebrar o código atual, este é inclusive o objetivo deste file, manter tudo na mesma versão.
> 
> Como existem mais de sete mil mudanças no file e nenhum novo pacote adicionado ao `package.json`, acredito que em algum momento você pode ter o deletado e durante a reinstalação dos pacotes o próprio yarn baixou diversas dependências mais atualizadas.
> 
> Tente, utilizando o git, desfazer as mudanças apenas para este file, atualizando-o com a branch main.

2022-04-03 21:19 UTC, frattezi commented on src/components/AddItemForm.tsx
> +export interface TaskListMap {
Seria um Task**List**Map? Ou uma TaskMap, ou até melhor, uma Task!

2022-04-04 11:08 UTC, Filipe-barbosa commented on src/components/TaskDashboard.tsx
> +      {taskList.map((element) => {
element e um bom nome ?

2022-04-04 11:08 UTC, Filipe-barbosa commented on src/App.tsx
> -  const [taskList, setTaskList] = useState({
esse código foi embasado de algum outro? pelas alteracoes ele parece que na maiin a funcionalidade ja esta implementada

2022-04-05 20:00 UTC, frattezi commented on src/App.tsx
> +  function addNewTask(taskContent: string) {
nice!

2022-04-06 19:57 UTC, frattezi approved these changes
Apenas alguns comentários menores, questão de nomeação de variáveis e espaçamentos no código. Já estou dando o approve, mas se os comments fizerem sentido para você, adicione-os antes do merge ^^

2022-04-06 19:57 UTC, frattezi commented on src/App.tsx
> +    { task: 'Model Task Example', completed: false, id: '123456' },
Acho que aqui nem precisaria desse template, poderia inicializar com a listagem vazia mesmo. Mas é apenas uma sugestão, nada impeditivo

2022-04-06 19:57 UTC, frattezi commented on src/App.tsx
> +    const myNewTask = {
poderia ser apenas newTask

2022-04-06 19:57 UTC, frattezi commented on src/App.tsx
> +  const [taskList, setTaskList] = useState<TaskType[]>([
Acho que o código ficaria mais agradável de ler tendo um Enter serparando estas declarações.
algo assim:
```javascript
function App() {
  const bla...
  const tcha... // 2x Enter aqui
 
  function tchaca() {}... // 2x Enter aqui

  return
}
```

2022-04-06 19:57 UTC, frattezi commented on src/components/AddItemForm.tsx
> +  const [userInput, setUserInput] = useState<string>('');
Mesmo que o comment acima, poderia ter dado 2 enters entre blocos de constants, functions e returns

2022-04-07 02:51 UTC, merged