Vzsoares/implement context
vzsoares/todo-list pull request #3
Opened 2022-04-14 01:38 UTC by vzsoares

## Description

This PR implements **react context** to the code

## About

- does not changes main logic

2022-04-14 13:11 UTC, marco-souza requested changes

2022-04-14 13:11 UTC, marco-souza commented on src/AppContext.tsx
> +const defaultContext = {
ta faltando o tipo desse objeto

2022-04-14 13:11 UTC, marco-souza commented on src/AppContext.tsx
> +  checkTaskBox() {},
Eu particularmente acho estranho essa forma de declarar funçoes, pois perdemos a legibilidade e pode gerar confusao. Eu faria algo assim

```js
{ 
  addTask: () => {},
  ...
}
```

2022-04-14 13:11 UTC, marco-souza commented on src/AppContext.tsx
> +function AppContextProvider({ children }: { children: ReactNode }) {
Faltou seprar o tipo em uma interface de props

```js
interface Props { 
  children: ReactNode;
}
```

2022-04-14 13:11 UTC, marco-souza commented on src/AppContext.tsx
> +  const AppContextData = useMemo<IAppContextData>(() => {
Tudo que não for Tipo, Classe ou componente react, não pode começar com maisculo. Isso é uma conveção do JS

No caso `AppContextData` não é um tipo, ou classe ou componente, deveria começar com letra minuscula

2022-04-14 13:11 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +      {(context) => {
Isso aqui nao ta legal. Da uma olhada no `useContext` do react.

Essa forma que vc ta usando caiu em desuso após a versão 16 do react. Estamos na versão 18.

2022-04-14 13:11 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +  const { taskList } = useContext(AppContext);
Aqui ja ficou mais interessante, do jeito mais atual

2022-04-14 13:11 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +      setDisplayedTasks(taskList.filter((task: ITaskItem) => !task.completed));
Pq isso foi tipado?
O TS não consegue inferir o tipo baseado na lista?

2022-04-14 13:11 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +      setDisplayedTasks(taskList.filter((task: ITaskItem) => task.completed));
mesma coisa

2022-04-14 13:11 UTC, marco-souza commented on src/components/TaskItem.tsx
> +function TaskItem({ taskData }: { taskData: ITaskItem }) {
props

2022-04-14 13:11 UTC, marco-souza commented on src/components/TaskItem.tsx
> +        return (
jeito legado de acessar o context

2022-04-14 15:19 UTC, frattezi reviewed
Muito massa o uso do context Zenha, acho que o principal é passar tudo para o padrão mais conciso de hooks e usar esse pattern em todos os consumidores. Mas muito bom, o código ficou muito limpo!

2022-04-14 15:19 UTC, frattezi commented on src/App.tsx
> +import { AppContextProvider } from './AppContext';
Eu acho que poderia especificar o nome do context, como: `TodoContext`  ou `TodoFormContext` sei que neste app esta é a única funcionalidade mas só para especificar uma vez que o contexto cumpre uma função muito objetiva.
Normalmente temos múltiplos contextos em um App ^^

2022-04-14 15:19 UTC, frattezi commented on src/App.tsx
> +    <AppContextProvider>
Ai sim, olha a elegância 🚀 🚀 🚀

2022-04-14 15:19 UTC, frattezi commented on src/components/AddItemForm.tsx
> +      {(context) => {
Acredito que o próprio AppContext já poderia exportar o useAppContext, facilitando o hook  e diminuindo os imports pros usuários

2022-04-14 15:19 UTC, frattezi commented on src/components/AddItemForm.tsx
> +    <AppContext.Consumer>
Fica meio crazy, concordo com marquinhos

2022-04-14 19:32 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +      setDisplayedTasks(taskList.filter((task: ITaskItem) => !task.completed));
tava dando erro no typescript ... vou tentar tirar

2022-04-14 19:37 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +      setDisplayedTasks(taskList.filter((task: ITaskItem) => !task.completed));
Eh, provavelmente algo no uso do context

2022-04-14 19:38 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +      {(context) => {
fazer um `const useAppContext = (): IAppContext => useContext(AppContext)` né?

2022-04-14 19:48 UTC, vzsoares commented on src/components/TaskItem.tsx
> +function TaskItem({ taskData }: { taskData: ITaskItem }) {
como é um só eu achei q nem precisava , o felipe tinha falado com o mamao antes q um só dava nd

2022-04-15 14:37 UTC, Guilherme-BS reviewed
uso do contexto ficou muito elegante hehe se puder me dar uma moral com isso depois

2022-04-18 19:51 UTC, marco-souza approved these changes
Eita, ficou elegante pra carai! 🎩 👏👏
Ship it! 🚢

2022-04-18 20:07 UTC, frattezi approved these changes
Desce o dedo

2022-04-18 21:10 UTC, merged